<?php

// autoload_52.php generated by xrstf/composer-php52

require_once dirname(__FILE__) . '/composer'.'/autoload_real_52.php';

return ComposerAutoloaderInit8a3ddf08f6ae3cdbe7ba2ea836a3d48d::getLoader();
